### ISSUE TITLE
panic diff 2 passwords

### ISSUE THREAD

**Issue by opensource21** [Narigo/keepass-diff#29]
I tried:
`keepass-diff Keypass.kdbx  Keypass.sync-conflict-20200815-143003-TOI2QOM.kdbx --passwords geheim --keyfiles master.key`

and get
```
thread 'main' panicked at 'Error opening database A: DatabaseIntegrity { e: Crypto { e: BlockMode { e: BlockModeError } } }', /home/niels/.cargo/registry/src/github.com-1ecc6299db9ec823/keepass-diff-1.0.1/src/main.rs:153:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
   3: keepass_diff::main
```

or 
```
thread 'main' panicked at 'Error opening database A: DatabaseIntegrity { e: Crypto { e: BlockMode { e: BlockModeError } } }', /home/niels/.cargo/registry/src/github.com-1ecc6299db9ec823/keepass-diff-1.0.1/src/main.rs:153:18
stack backtrace:
   0:     0x5596163cc1d0 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x5596163cc1d0 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x5596163cc1d0 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x5596163cc1d0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x5596163e7d4c - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x5596163c9402 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x5596163ce5bd - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x5596163ce5bd - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x5596163ce5bd - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x5596163ce268 - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x5596163ceca1 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x5596163ce849 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:     0x5596163cc63c - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x5596163ce809 - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:     0x5596163e6db1 - core::panicking::panic_fmt::h48c31e1e3d550146
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:     0x5596163e6bd3 - core::option::expect_none_failed::h6154dc750ae47ade
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
  16:     0x559616306757 - keepass_diff::main::h24d0ebd4f84bfd4a
  17:     0x5596162fca1a - std::sys_common::backtrace::__rust_begin_short_backtrace::h54c754f1c3ec8729
  18:     0x5596162fd868 - std::rt::lang_start::{{closure}}::h84af0d8e2e4a1582
  19:     0x5596163cf1b7 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::he179d32a5d10d957
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:259
  20:     0x5596163cf1b7 - std::panicking::try::do_call::hcb3d5e7be089b2b4
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381
  21:     0x5596163cf1b7 - std::panicking::try::h7ac93b0cd56fb701
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345
  22:     0x5596163cf1b7 - std::panic::catch_unwind::h7b40e396c93a4fcd
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382
  23:     0x5596163cf1b7 - std::rt::lang_start_internal::h142b9cc66267fea1
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:51
  24:     0x559616307042 - main
  25:     0x7fec0f28e840 - __libc_start_main
  26:     0x5596162f1729 - _start
  27:                0x0 - <unknown>
```

what's wrong?

**Comment by Narigo** [comment]
Can you open both files with your regular keepass client? `DatabaseIntegrity` sounds like it cannot be opened

**Comment by opensource21** [comment]
Interesting: If I use the wrong password I get
```
thread 'main' panicked at 'Error opening database A: DatabaseIntegrity { e: InvalidKDBXVersion { version: 3041655653, file_major_version: 0, file_minor_version: 3 } }', /home/niels/.cargo/registry/src/github.com-1ecc6299db9ec823/keepass-diff-1.0.1/src/main.rs:153:18
```

And yes I double-check that the files could be read with KeepassX. Even with the correct password the panic is still the same :thinking: Curious that the behaviour change after reboot.

**Comment by opensource21** [comment]
Yes I double-check that the files could be read with KeepassX.

**Comment by Narigo** [comment]
I have updated the `keepass` dependency in the latest release now. The newest version of keepass-diff is `1.1.0` - maybe it's possible with this version?

**Comment by opensource21** [comment]
Thanks for the try. It looks like the same error to me :-/
```
thread 'main' panicked at 'Error opening database A: DatabaseIntegrity { e: Crypto { e: BlockMode { e: BlockModeError } } }', /home/niels/.cargo/registry/src/github.com-1ecc6299db9ec823/keepass-diff-1.1.0/src/main.rs:151:18
stack backtrace:
   0:     0x56172c2ca400 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x56172c2ca400 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x56172c2ca400 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x56172c2ca400 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x56172c2e63dc - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x56172c2c7632 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x56172c2cc7ed - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x56172c2cc7ed - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x56172c2cc7ed - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x56172c2cc498 - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x56172c2cced1 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x56172c2cca79 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:     0x56172c2ca86c - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x56172c2cca39 - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:     0x56172c2e5441 - core::panicking::panic_fmt::h48c31e1e3d550146
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:     0x56172c2e5263 - core::option::expect_none_failed::h6154dc750ae47ade
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
  16:     0x56172c2023b4 - keepass_diff::main::h84b87b6954612b5f
  17:     0x56172c1f861a - std::sys_common::backtrace::__rust_begin_short_backtrace::heb2b1f6f74d38100
  18:     0x56172c1f8b88 - std::rt::lang_start::{{closure}}::hb70420fe8bc952ec
  19:     0x56172c2cd3e7 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::he179d32a5d10d957
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:259
  20:     0x56172c2cd3e7 - std::panicking::try::do_call::hcb3d5e7be089b2b4
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381
  21:     0x56172c2cd3e7 - std::panicking::try::h7ac93b0cd56fb701
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345
  22:     0x56172c2cd3e7 - std::panic::catch_unwind::h7b40e396c93a4fcd
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382
  23:     0x56172c2cd3e7 - std::rt::lang_start_internal::h142b9cc66267fea1
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:51
  24:     0x56172c202da2 - main
  25:     0x7fd28392d840 - __libc_start_main
  26:     0x56172c1ed519 - _start
  27:                0x0 - <unknown>
```

**Comment by Narigo** [comment]
I have no idea why this fails. Can you provide some kind of reproducer so I can have a closer look? It might be an issue with the underlying library but without a reproducer I assume this is going to be hard to fix...

**Comment by opensource21** [comment]
I will put it on my todo-list (but it's unfortunately long).

**Comment by opensource21** [comment]
Found the problem. I used an old 64 bit-Key. One app warns me that this is old and I renew the keyfile. Now the diff works.

**Comment by Narigo** [comment]
Thanks for the heads-up @opensource21 ! I'll close this now. If you need support for such a key and it's specified somewhere that it should work, you could report it to the underlying [keepass-rs](https://github.com/sseemayer/keepass-rs/) library and ask for support
